name: npm publish

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - uses: oven-sh/setup-bun@v2

      - run: |
          set -ex
          cd cli && bun i && cd ..
          bun sh/npmPublish.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
